### ISSUE TITLE
Composer junction of file creates invalid link in shared space of host

### ISSUE THREAD

**Issue by martin55** [winnfsd/vagrant-winnfsd#131]
Windows 10 Pro
Homestead 9.4
Vagrant 2.2.7
Host: Ubuntu 18.04.4 LTS

Homestead.yaml
```
folders:
    - map: C:/Users/Documents/git
      to: /home/vagrant/Code
      type: "nfs"
```

In my case when I run composer on Windows10, it creates junctions of vendor folders. All seems to work on the Win10 side. But when I ssh to homestead host, I can see links are invalid (marked as red. It created something but somehow ubuntu cannot read it properly). When I create links manually or through composer in host, it seems to working in both systems.

Is it supporting symlinks (junctions) created on Win10? Thank you for advices what could be wrong.
