### ISSUE TITLE
mount.nfs: Connection timed out

### ISSUE THREAD

**Issue by loving-irene** [winnfsd/vagrant-winnfsd#141]
### environment
win11
vagrant 2.3.3
virtualbox 

vagrant install plugin vagrant-winnfsd

### Issue
use this homestead.yaml
```
folders:
     ...
    - map: D:\lovan\codeSrc\mexico
      to: /home/vagrant/code/mexico
      type: "nfs"
    - map: D:\lovan\codeSrc\mexico-new
      to: /home/vagrant/code/mexico-new
      type: "nfs"
```
get error message
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,vers=3,udp,nolock 192.168.56.1:/D/lovan/codeSrc/mexico-new /home/vagrant/code/mexico-new

Stdout from the command:

Stderr from the command:

mount.nfs: Connection timed out
```

change to
```
folders:
     ...
    - map: D:\lovan\codeSrc\mexico
      to: /home/vagrant/code/mexico
      type: "nfs"
```
it works,another
```
folders:
     ...
    - map: D:\lovan\codeSrc\mexico-new
      to: /home/vagrant/code/mexico-new
      type: "nfs"
```
still work

`mexico` and `mexico-new` both exist,it not work.

i have no idea about that
